package com.vdcrx.rest.domain.enums;

/**
 * Veterinarian specialty types
 *
 * @author Ranel del Pilar
 */

public enum VeterinarianSpecialtyType {
    ANESTHESIA,
    ANIMAL_WELFARE,
    BEHAVIOR,
    DENTISTRY,
    DERMATOLOGY,
    EMERGENCY_AND_CRITICAL_CARE,
    INTERNAL_MEDICINE_CARDIOLOGY,
    INTERNAL_MEDICINE_NEUROLOGY,
    INTERNAL_MEDICINE_ONCOLOGY,
    LABORATORY_ANIMAL_MEDICINE,
    MICROBIOLOGY,
    NUTRITION,
    OPHTHALMOLOGY,
    PATHOLOGY,
    PHARMACOLOGY,
    POULTRY,
    PREVENTIVE_MEDICINE,
    RADIOLOGY,
    SPORTS_MEDICINE_AND_REHABILITATION,
    SURGERY_ORTHOPEDICS,
    SURGERY_SOFT_TISSUE,
    THERIOGENOLOGY,
    TOXICOLOGY,
    PRACTITIONER_AVIAN,
    PRACTITIONER_EQUINE,
    PRACTITIONER_BEEF_CATTLE,
    PRACTITIONER_FELINE,
    PRACTITIONER_CANINE_FELINE,
    PRACTITIONER_EXOTIC_COMPANION_MAMMAL,
    PRACTITIONER_FOOD_ANIMAL,
    PRACTITIONER_DAIRY,
    PRACTITIONER_GENERAL,
    PRACTITIONER_REPTILE_AMPHIBIAN,
    PRACTITIONER_SWINE_HEALTH_MANAGEMENT,
    ZOOLOGICAL_MEDICINE,
    OTHER
}
